version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es
    environment:
      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - discovery.type=single-node
#      - xpack.security.enabled=false
      - TAKE_FILE_OWNERSHIP=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
     - ./es/data:/usr/share/elasticsearch/data
     - ./es/logs:/usr/share/elasticsearch/logs
     - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
     - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    ports:
      - "5601:5601"    
    links:
      - es
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

#  web:
#    image: httpd
#    container_name: httpd
#    ports:
#      - "80:80"
#    links:
#      - fluentd
#    logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: httpd.access

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/data:/data
    links:
      - "es"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  

#  filebeat:
#    build: ./filebeat
#    container_name: filebeat
#    volumes:
#      - ./fluentd/data:/data
#    links:
#      - es
#      - kibana
 
networks:
  default:
    external:
      name: elk_net
